// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZKNkRsIJLZR9FOxyazwd7stGM0ToYp0A',
    appId: '1:1088300194458:web:f74a808bf6a450e7fd9d23',
    messagingSenderId: '1088300194458',
    projectId: 'dadob-92dfe',
    authDomain: 'dadob-92dfe.firebaseapp.com',
    storageBucket: 'dadob-92dfe.appspot.com',
    measurementId: 'G-BYLF3G8V7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD63aj63z_S7uHNRmtECxQkEHyPCnhVbpc',
    appId: '1:1088300194458:android:87d62703971f0c43fd9d23',
    messagingSenderId: '1088300194458',
    projectId: 'dadob-92dfe',
    storageBucket: 'dadob-92dfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtEsWv75WPlXrxL25dem7H_Xsc0EgQYYQ',
    appId: '1:1088300194458:ios:ffa5b47e5d6dbf69fd9d23',
    messagingSenderId: '1088300194458',
    projectId: 'dadob-92dfe',
    storageBucket: 'dadob-92dfe.appspot.com',
    iosBundleId: 'com.example.testt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtEsWv75WPlXrxL25dem7H_Xsc0EgQYYQ',
    appId: '1:1088300194458:ios:9934f450cdc812f6fd9d23',
    messagingSenderId: '1088300194458',
    projectId: 'dadob-92dfe',
    storageBucket: 'dadob-92dfe.appspot.com',
    iosBundleId: 'com.example.testt.RunnerTests',
  );
}
